[profile.default]
src = "contracts"
libs = ["node_modules"]
remappings = ["@hyperlane/=node_modules/@hyperlane-xyz/core/contracts/"]

[profile.wnoble]
optimizer = true
optimizer_runs = 10000

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
