name: Deploy to GitHub Pages

on:
  push:

jobs:
  build:
    name: Build Explorer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: 'true'
      - uses: actions/setup-node@v5
        with:
          cache: yarn

      - run: yarn install --frozen-lockfile
      - run: yarn build

      - uses: actions/upload-pages-artifact@v4
        with:
          path: dist

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
